[build]
builder = "nixpacks"
buildCommand = "npm run install:all && npm run build"

[deploy]
startCommand = "npm run start"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[[deploy.healthcheckPath]]
path = "/api/health"
